### ISSUE TITLE
Changes of permissions might require to relogin

### ISSUE THREAD

**Issue by corvus-ch** [appuio/appuio-cloud-docs#12]
When permissions of my user are changed while I am logged in the OpenShift web console, those changes might be picked up. Instead I must logout and login again to have those changes active.

**Comment by akosma** [comment]
Is this still an issue?

**Comment by corvus-ch** [comment]
No, this is no longer an issue. Tested with the following procedure:

1. Login as unprivileged user without access to a test namespace → the namespace is not listed
2. Added that user as a subject to the  `namepsace-owner` RoleBinding in the test namespace → the namespace immediately showed up (`/add/all-namespaces`).
