### ISSUE TITLE
Migration Tutorial: From Public to Cloud

### ISSUE THREAD

**Issue by tobru** [appuio/appuio-cloud-docs#39]
* Point to differences page (https://docs.appuio.cloud/user/explanation/differences-to-public.html)
* DNS
* Let's Encrypt (Route -> Ingress)
* Storage (Persistent Volumes)
* Container Images

**Comment by akosma** [comment]
Will there be a "Part 2"? Should part 1 and 2 be different pages in the documentation, or just a followup in the same page?

**Comment by tobru** [comment]
I can't remember why it was called "Part 1". Therefore I removed it from the title.

**Comment by megian** [comment]
@tobru This issue is concluded from my point of view.

**Comment by tobru** [comment]
It's deployed: https://docs.appuio.cloud/user/tutorials/migration.html
