### ISSUE TITLE
Dokumentation von "Namespace" bei Templates

### ISSUE THREAD

**Issue by peter-englmaier** [appuio/appuio-cloud-docs#69]
Hallo

Ein kleiner Wunsch für bessere Dokumentation. 

Ich habe mit eine Postgres DB mit  Developer->+App->Postgres erstellt und mich gewundert warum sie nicht startet.

Nach einiger Sucherei habe ich die Ursache funden: ich habe das Feld "Namespace" mti dem Namespace  ausgefüllt in dem ich die Datenbank verwenden möchte. Das ist aber nicht richtig, es muss "openshift"  eingetragen werden, weil das der Namespace ist in dem das Postgres Image gebaut wurde (ImageStream Origin). 

Die Information in der Eingabemaske ist für Anfänger unverständlich, insbesondere wenn man meint schon Vorwissen aus Kubernetes mitzubringen. 

Bitte die Verwendung von Templates in der Dokumentation erklären und ganz fett markiert darauf hinweisen, was hier mit "Namespace" gemeint ist, was ein ImageStream ist, und wo dokumentiert ist wie man diese ggf. selbst erstellen kann (falls vorgesehen). 

Falls es möglich ist die Templates anzupassen, dann könnte unter Namespace folgender Hinweis stehen:
"This template consumes image from another openshift namespace. Please do not edit this field, unless necessary."

Gruss, Peter

**Comment by akosma** [comment]
Danke für deine Anfrage! Wir werden in der Dokumentation eine neue Seite speziell für dieses Problem einrichten. Ausserdem fügen wir einen Haftungsausschluss hinzu, um die Nutzer vor OpenShift-spezifischen Funktionen zu warnen, die in Standard-Kubernetes nicht verfügbar sind, und um ihnen zu zeigen, wo sie entsprechende Informationen finden können.
