### ISSUE TITLE
Document login from the command line 

### ISSUE THREAD

**Issue by corvus-ch** [appuio/appuio-cloud-docs#80]
On APPUiO Cloud, login from the command line does not work using the `--username` and `--password` options. So the alternative is to visit the Web Console and navigate to the "Copy login command" and copy the token from there.

There is also another, less documented way that is faster: the option `--server`.

```sh
oc login --server=https://api.<zone>.appuio.cloud:6443
```

This will print the URL directly, bringing you to the page where you can copy the login command.

**Comment by akosma** [comment]
This is part of an Antora partial, reused across various pages, including this one: 
https://docs.appuio.cloud/user/how-to/use-oc-cli.html

Is this ticket done?
