### ISSUE TITLE
APPUiO Cloud Portal User Guide

### ISSUE THREAD

**Issue by tobru** [appuio/appuio-cloud-docs#97]
The APPUiO Cloud Portal needs a user guide which explains the possibilities and individual features. Plus we need to document the concepts in use: Organization, Team, Zone.

**Comment by akosma** [comment]
Shouldn't this issue be in https://github.com/appuio/cloud-portal instead? So that we add a `docs` folder there with the documentation of the project in situ with its code.

**Comment by tobru** [comment]
Feel free to add the documentation directly there. It should be integrated in docs.appuio.cloud in the end... But with Antora: No problem.

**Comment by akosma** [comment]
Following here: https://github.com/appuio/cloud-portal/pull/148
